markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/oakland-pattern-portfolio"

version: 2.3.3

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/ObjectiveSubject/oakland-pattern-portfolio
